services:
  - type: web
    name: rise-app
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ENV
        value: production
      - key: REQUIRE_HTTPS
        value: true
      - key: CORS_ORIGINS
        value: "https://your-frontend-domain.com" # Update this to your deployed frontend domain

      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        sync: false
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0 # Adjust according to the current environment
