services:
  - type: web
    name: secure-vibe-backend
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ENV
        value: production
      - key: CORS_ORIGIN_LIST
        value: '["*"]' # Adjust this as needed
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "43200" # 30 days
      - key: PYTHON_VERSION
        value: 3.12.0 # Adjust according to the current environment
